vuejs/devtools

- packages/core/src/vite-rpc/assets.ts
> fix: remove public prefix to resolve vite assets warning

- packages/core/src/bridge/devtools.ts
- packages/playground/src/App.preview.vue
- packages/playground/src/stores/index.ts
fix: #121
Deserialize the getters from Pinia's `inspector-state:send` payload.
to be:
https://github.com/vuejs/devtools-next/assets/22590005/c7ff849d-eb51-4249-9d3a-3930468b4fdc
> fix(pinia): passing `getters` on `inspectorStateUpdated`

- packages/client/src/components/inspector/InspectorStateField.vue
- packages/client/src/pages/components.vue
- packages/client/src/pages/pinia.vue
- packages/client/src/pages/router.vue
fix: #110 
Before:
The +/- buttons keep flickering (unnecessary rerender) and the whole InspectorState panel tree keeps rerendering.
https://github.com/vuejs/devtools-next/assets/22590005/75fa0d5f-b69b-4fea-b4c9-8ada25194239
After:
Only the count is updated.
https://github.com/vuejs/devtools-next/assets/22590005/94760fbd-c6a1-49ff-a64d-65738672b822
The collapsed state is always re-created after the component is updated and the current state is discarded.
Merge the current state into the re-calculated state.
> fix: redundant re-render and loss of collapsed state for inspector tree/state component

- packages/client/src/components/inspector/InspectorState.vue
- packages/client/src/components/inspector/InspectorStateField.vue
- packages/client/src/components/inspector/InspectorStateType.vue
The same name property in different roots can be expanded unexpectedly when toggling one of the roots.
Take `rootId` into consideration when composing the expanding key.
Before:
https://github.com/vuejs/devtools-next/assets/22590005/b4f4f518-053e-409c-b7cd-bc45e0e02342
After:
https://github.com/vuejs/devtools-next/assets/22590005/acd014b8-cc87-4453-b8f3-e1f727572922
> fix(client): unique collapse id for inspector state tree

- docs/.vitepress/theme/style.css
The contrast is really bad (under A, see https://coolors.co/contrast-checker/ffffff-46e392) for the brand button (Get Started button on the index page), as seen in the screenshot bellow:
[![image](https://github.com/vuejs/devtools-next/assets/110247388/78cf5000-194a-4fb9-883f-f74e1ac57ae5)](https://coolors.co/contrast-checker/ffffff-46e392)
To fix it, I've changed the button's text to black (--vp-c-black) that improves the buttons contrast to over AAA (see https://coolors.co/contrast-checker/000000-46e392)
> chore(docs): changed brand button text color for better contrast

- packages/devtools-kit/src/core/component-inspector/index.ts
> fix: selecting components highlighting bounds incorrectly

- packages/client/src/composables/state-tab.ts
Errors occur when there are pinned tabs and when the Scrollable Sidebar is canceled. After refreshing the page, the panel is broken. see video below:
https://github.com/vuejs/devtools-next/assets/3993028/c1f99c9f-46d9-423c-831f-d13389bf8f4c
> fix(client): sort error of pinned tabs

- packages/devtools-kit/src/core/component/state/constants.ts
- packages/devtools-kit/src/core/component/state/process.ts
`Set.has` has O(1) performance, which is faster than `Array.includes`'s O(n).
> perf: use `Set.has` instead of `Array.includes`

- packages/client/src/components/inspector/InspectorDataField/Actions.vue
- packages/client/src/components/inspector/InspectorStateField.vue
- packages/devtools-kit/src/core/component/state/format.ts
- packages/devtools-kit/src/shared/util.ts
fix: #127
- Abstract function getRawValue.
- Use deserialized value on editing custom objects.
https://github.com/vuejs/devtools-next/assets/22590005/de5ac8eb-a085-432c-9ef2-899027b71f81
> fix(client): deserialize issue on editing custom property

- packages/client/src/components/WaitForConnection.vue
- packages/client/src/components/assets/AssetDetails.vue
- packages/client/src/components/code/CodeSnippets.vue
- packages/client/src/composables/editor.ts
- packages/ui/src/components/Input.vue
Preview
https://github.com/vuejs/devtools-next/assets/49969959/130d88fb-b16e-4cde-b933-7d6eea15b40f
> feat(electron): copy button of connection page

- packages/client/src/components/inspector/InspectorDataField/Actions.vue
- packages/devtools-kit/src/core/component/state/editor.ts
Fix: #161
- Fix the issue that the reactive object cannot be passed to `window.postMessage`
- Enable deletion of property on Map/Set
- Fix clicking on the deletion button will accidentally toggle the property.
FYI: There are still some problems with deserializing/serializing on custom objects.
We can fix it on another PR.
> fix(client/bridge): enable deletion of property on Map/Set

- packages/devtools-kit/src/core/component/state/__tests__/format.spec.ts
- packages/devtools-kit/src/core/component/state/format.ts
- packages/devtools-kit/src/core/component/types/state.ts
Custom objects may nest another custom object in some situations (Eg. Inspect Pinia's root state)
Fix:
- Resolve the display name and raw value from the object recursively.
- Add some tests for `function getRawValue` and `function getRawValue`
> fix(client): resolve nested custom object

- docs/guide/features.md
This PR is to update `vite-plugin-inspect` URL in the docs.
The package of the latest version `v0.8.1` is in use in this repo. But the original URL links to a forked repo with the previous version.
> docs: fix `vite-plugin-inspect` repo url

- packages/client/src/components/inspector/InspectorDataField/EditInput.vue
- packages/client/src/components/inspector/InspectorStateField.vue
- packages/devtools-kit/src/core/component/state/__tests__/format.spec.ts
- packages/devtools-kit/src/core/component/state/editor.ts
- packages/devtools-kit/src/core/component/state/format.ts
- packages/devtools-kit/src/core/component/state/util.ts
- packages/devtools-kit/src/shared/util.ts
Ref: https://github.com/vuejs/devtools-next/discussions/147
As discussed in #147, Editing the state will always cause unintentional type conversion.
Rewrite the serialization and deserialization procedure for submitting and editing. So the submit value can accept various 
native types.
> fix(client): error type conversion on editing 

- packages/client/src/assets/styles/main.css
- packages/client/src/components/assets/AssetDetails.vue
- packages/client/src/components/assets/FilepathItem.vue
> feat(client): improve ui of assets page

- packages/client/src/components/inspector/InspectorDataField/EditInput.vue
- Check the validity of the input value when submitting.
- Show the cancel button if the input value is invalid.
- Add simple tooltip for the warning icon.
> feat(client): improve behavior of `EditInput` component

- .gitignore
- package.json
- packages/browser-extension/tsup.config.ts
- packages/core/package.json
- packages/core/tsup.config.ts
- packages/devtools-api/package.json
- packages/devtools-api/tsup.config.ts
- packages/devtools-kit/package.json
- packages/devtools-kit/tsup.config.ts
- packages/devtools/hook.d.ts
- packages/devtools/package.json
- packages/devtools/tsup.config.ts
- packages/electron/cli.d.ts
- packages/electron/package.json
- packages/electron/scripts/build.ts
- packages/schema/global.d.ts
- packages/schema/package.json
- packages/schema/src/index.ts
- packages/schema/tsup.config.ts
- packages/schema/types.d.ts
- packages/shared/package.json
- packages/shared/tsup.config.ts
- pnpm-lock.yaml
> chore: fix package export types

- packages/client/src/pages/assets.vue
- packages/core/src/bridge/devtools.ts
- packages/core/src/vite-rpc/assets.ts
- packages/core/src/vite-rpc/client.ts
- packages/core/src/vite-rpc/types.ts
- packages/vite/src/vite.ts
This PR is to close #200.
With reactively updating assets, it seems that there is no need to add a refresh button.
> feat: update assets in real time

- packages/devtools-kit/src/core/component/state/custom.ts
- packages/devtools-kit/src/core/component/state/editor.ts
Close #216
- Use object UI to display native object Map.
- Fix editing on native object Map.
> feat(client): improve inspector UI of Map data type

- packages/devtools-kit/src/core/component/state/__test__/editor.test.ts
- packages/devtools-kit/src/core/component/state/editor.ts
- Use worst: O(n + m), best: O(n) algorithm on RefStateEditor.set.
- Fix the key that cannot be deleted if the new and old value have the same length of keys.
> perf: improve RefStateEditor.set performance

- packages/client/src/components/inspector/InspectorStateField.vue
The value of the drafted new prop is submitted as a string, deserialize the string value by `toSubmit`
Before:
After:
> fix(client): deserialize value on drafting new prop

- packages/client/src/components/inspector/InspectorStateField.vue
Fix the issue that can not draft prop on an empty object.
> fix(client): enable drafting prop on empty object

- packages/client/src/components/inspector/InspectorDataField/Actions.vue
- packages/client/src/composables/inspector.ts
The add option should not appear when the value is null.
Before:
After:
> fix(client):should not provide editing(add/subtract) feature for null

- packages/client/src/components/common/SideNav.vue
> chore: improve sidebar style

- packages/client/src/pages/pinia.vue
- packages/core/src/bridge/devtools.ts
- packages/core/src/bridge/types.ts
- packages/core/src/bridge/user-app.ts
- packages/devtools-kit/src/api/api.ts
- packages/devtools-kit/src/api/hook.ts
- packages/devtools-kit/src/api/on.ts
Fix: #243
Use `API: notifyComponentUpdate` in old devtool to update the status of Pinia module, refetch the Pinia state when `notifyComponentUpdate` called.
> fix(client, bridge): update pinia status when module loaded

- docs/guide/standalone.md
- packages/electron/src/index.ts
- packages/playground/termui/src/main.ts
feat(standalone) Add defaults host/port for func: connect
> feat(standalone): add default host/port for connect function

- packages/vite/src/overlay.js
see: #123 
Currently the assets for the overlay are loaded from just a path, if the `clientHost` config is set it should load the assets from this URL
> fix(vite): respect `clientHost` option for overlay asset URLs

- packages/devtools-api/src/index.ts
> fix(api): export `setupDevtoolsPlugin` function

- eslint.config.js
refer: https://github.com/antfu/eslint-ts-patch/issues/5
> chore: use js config file for eslint

- packages/devtools-kit/__tests__/api/api.test.ts
- Use vi.waitFor instead of unstable setTimeout
- Fix test case `should work w/ addInspector api`, which currently always passes
- Add test case for #247
> tests(devtools-kit): use `vi.waitFor` instead of `setTimeout` and add test for #247

- .gitignore
- packages/client/scripts/pre-build.ts
- packages/client/vite.config.ts
- packages/client/vite.lib.config.ts
- packages/vite/package.json
- packages/vite/src/dir.ts
Migrate to the top-level client directory to avoid build order restrictions.
> refactor: migrate vite client bundle files directory

- packages/client/src/pages/pinia.vue
Fix: #263
Reverting modification: https://github.com/vuejs/devtools-next/pull/244/files#diff-42f4e2af39f7cbaa4712c9e872faf3068c7327869f5da043054fa298e60a2fc8R37-R53
Refetching the state on component updating will unexpectedly update the current state.
FYI: #244 aimed to resolve dynamic pinia module registration, but it was resolved by #247.
So reverting this logic does not affect dynamic module registration.
> fix(client): revert getting pinia state on update

- packages/client/src/components/inspector/InspectorTree.vue
- packages/client/uno.config.ts
Truncate the path to account for custom regex in the route params. Fixes #235.
To illustrate, you can define a route with custom regex in the param as seen here for a UUID:
```typescript
{
path: '/hello/:id([0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12})',
component: () => import('./pages/Hello.vue'),
name: 'hello',
}
```
> fix(client): route param regex overflows container

- packages/client/src/components/inspector/InspectorStateField.vue
- packages/devtools-kit/__tests__/component/editor.test.ts
- packages/devtools-kit/src/core/component/state/editor.ts
- Optimize editing on the native set.
- Adding values to set.
- Deleting object value in the set.
- Disable modification on value in the set.
- Value in set should be unable to be modified. (can be added or removed)
- Add tests for devtools-kit/editor.
> feat(kit): optimize editing on native set

- packages/client/src/components/inspector/InspectorDataField/EditInput.vue
- packages/devtools-kit/__tests__/component/format.test.ts
- packages/devtools-kit/src/core/component/state/custom.ts
- packages/devtools-kit/src/core/component/state/format.ts
- packages/devtools-kit/src/core/component/state/replacer.ts
- packages/devtools-kit/src/core/component/types/custom.ts
- packages/ui/src/components/Input.vue
- packages/ui/storybook/Input.story.vue
Use `input(type=datetime-local)` on editing the date object.
https://github.com/vuejs/devtools-next/assets/22590005/da6f46c1-b509-4f77-9ff7-1d4dd15233cc
> feat(client): use browser native UI on date editing

- packages/client/src/components/assets/AssetDetails.vue
- packages/client/src/components/graph/GraphDrawer.vue
- packages/client/src/components/pages/RoutesTable.vue
- packages/client/src/composables/open-in-editor.ts
- packages/client/src/pages/components.vue
- packages/core/src/bridge-events/devtools-actions.ts
- packages/devtools-kit/src/core/open-in-editor/index.ts
- packages/vite/src/modules/get-config.ts
- packages/vite/src/vite.ts
> fix: respect open-in-editor host option

- packages/client/src/composables/graph.ts
> fix(client): deduplicate node references in graph page

- packages/devtools-kit/src/core/component/tree/walker.ts
- packages/devtools-kit/src/core/index.ts
- packages/devtools-kit/src/hook/index.ts
- packages/devtools-kit/src/plugins/component.ts
- packages/shared/src/env.ts
Be related to:
https://github.com/nuxt/nuxt/issues/26461
https://github.com/nuxt/devtools/issues/634
> fix(kit): respect legacy devtools hook in nuxt app

- packages/devtools-kit/global.d.ts
- packages/devtools-kit/src/api/api.ts
- packages/devtools-kit/src/core/app-record/index.ts
- packages/devtools-kit/src/core/component/state/custom.ts
- packages/devtools-kit/src/core/component/tree/walker.ts
- packages/devtools-kit/src/core/component/utils/index.ts
- packages/devtools-kit/src/plugins/component.ts
- packages/devtools-kit/src/state/app-record.ts
- packages/devtools-kit/src/types/app.ts
Be related to https://github.com/nuxt/devtools/issues/640
> fix(kit): deconfliction variable-naming with legacy devtools

- packages/client/src/components/assets/AssetListItem.vue
- packages/client/src/components/assets/AssetPreview.vue
- packages/core/src/vite-bridge/module-types.ts
- packages/vite/src/modules/assets.ts
This PR is to add scanning `wasm` files in the `assets` tab.
Because there are no icons related to the wasm files in the `carbon` presets, so I use the `vscode-icons`
> feat(vite): support wasm asset file type

- packages/overlay/src/composables/position.ts
Also fixed the initial panel position issue.
| Before | After |
|--------|--------|
| ![20240403161139_rec_-convert](https://github.com/vuejs/devtools-next/assets/45714701/88035bc8-d3fb-40a9-b3d8-0cf409fe63f3) | ![20240403161356_rec_-convert](https://github.com/vuejs/devtools-next/assets/45714701/ad9470bf-b3cd-41df-bbe9-28470f59a9be) |
> refactor(overlay): get window size by `useWindowSize`

- packages/playground/applet/package.json
- packages/playground/basic/package.json
- packages/playground/multi-app/package.json
- packages/playground/ui/package.json
- pnpm-lock.yaml
This PR is to close #321.
After checking, only some repositories under `package/playground` don't set `type: "module"`. Sub packages such as `applet`, `client`, `overlay`, etc. have worked well with ESM.
> chore(playground): compatible with esm-only unocss

- package.json
- packages/applet/index.d.ts
- packages/applet/package.json
- packages/applet/tsconfig.json
- packages/applet/vite.config.ts
- pnpm-lock.yaml
This PR is to use `vite-plugin-dts` to emit dts files under the `package/applet` and update exports fields related to type declarations in the `package.json`.
> refactor(applet): use `vite-plugin-dts` to generate dts

- packages/overlay/src/composables/position.ts
Safe `window`  as `useEventListener` default target and it does not need to be in `onMounted`.
> chore(overlay): remove unnecessary safe `window`

- packages/vite/build.config.ts
- packages/vite/esbuild-shims/cjs-shim.ts
- packages/vite/package.json
Looks like `tsup` shim with our custom esbuild shim has come into conflict in cjs mode.
Revert to use `unbuild` for build, `tsup` for dev.
closes #331 , have tested.
> fix(vite): cjs compatible

- packages/client/src/components/assets/AssetDetails.vue
- packages/core/src/vite-bridge/module-types.ts
- packages/playground/basic/src/pages/Hey.vue
- packages/playground/basic/src/pages/Home.vue
- packages/vite/src/modules/assets.ts
This PR is related to #208.
It defines a new Vite server action `assets:get-asset-importers` to help to get the targeted asset's importers depending on Vite's module graph in the `AssetDetails`.
> feat(vite): show asset importers

- packages/applet/src/components/tree/TreeViewer.vue
To avoid duplicate css / redundant width calculation, only adding this to the root TreeView is necessary.
Previous:
After:
https://github.com/vuejs/devtools-next/assets/49969959/6d60091a-b53b-4b28-8907-942b7b13e608
> fix(applet): incorrect rendering on overflowed TreeViewer

- packages/devtools-kit/src/core/index.ts
- packages/playground/multi-app/src/main.ts
> fix: disconnect when all apps are unmount

- packages/client/src/components/CustomTabComponent.vue
- packages/client/src/components/common/IframeView.vue
- packages/client/src/components/common/SideNavItem.vue
- packages/client/src/components/common/SplitScreen.vue
- packages/client/src/components/common/TabsGrid.vue
- packages/client/src/constants/tab.ts
- packages/client/src/main.ts
- packages/client/src/pages/custom-tab-view.vue
- packages/client/src/pages/graph.vue
- packages/client/src/pages/overview.vue
https://github.com/vuejs/devtools-next/assets/49969959/1b0449bf-bada-4162-b814-5c9253bd8ce8
> feat: improve split screen

- packages/applet/src/components/basic/NodeTag.vue
- packages/applet/src/components/state/StateFieldEditor.vue
- packages/applet/src/components/state/StateFieldInputEditor.vue
- packages/applet/src/components/state/StateFieldViewer.vue
- packages/applet/src/modules/components/index.vue
- packages/client/src/components/assets/AssetDetails.vue
- packages/client/src/components/assets/FilepathItem.vue
- packages/client/src/components/common/SplitScreen.vue
- packages/client/src/components/inspector/InspectorDataField/Actions.vue
- packages/client/src/components/inspector/InspectorDataField/EditInput.vue
- packages/client/src/components/inspector/InspectorStateField.vue
- packages/ui/src/index.ts
since https://github.com/Akryum/floating-vue/commit/abf094fe1009e43b4a2b9827cbb7f57fe66fe333
We should use `vTooltip` instead.
> chore: use `vTooltip` instead of deprecated API

- packages/client/src/components/CommandPalette.vue
> fix: make `CommandPalette` component z-index maximum

- docs/guide/vite-plugin.md
I noticed this undocumented option
https://github.com/vuejs/devtools-next/blob/cdd7a294d5e734dff742a333111d7abaf6b6f4a1/packages/vite/src/vite.ts#L59-L64
> docs: component inspector option

- README.md
As the documentation structure is changed, the URL is no longer valid.
> docs: update contributing URL

- .github/workflows/autofix.yml
- .github/workflows/ci.yml
If the pnpm version is not the same as the project, the lockfiles of CI and local maybe differ, e.g [failed ci](https://github.com/vuejs/devtools-next/actions/runs/9283587663/job/25544254951)
> workflow: respect project pnpm version

- docs/guide/vite-plugin.md
> The other plugins (vue, vueJsx and nightwatchPlugin) all follow the same convention to have a lowercase at the start, so let's do the same for vueDevTools
Reference: https://github.com/vuejs/create-vue/pull/524
> docs: update vite plugin guide

- packages/applet/src/components/state/StateFieldViewer.vue
As described in title, the component module's state field viewer now allows users to select string values. 
This enhancement facilitates operations such as copying a portion of the text value or using the browser's context menu with a simple right-click.
Before: 
After:
> chore:  in component module's state field viewer, allow select-text for string fields

- packages/applet/src/components/tree/TreeViewer.vue
This PR implements double-clicking anywhere on the line to toggle the expansion status of the component tree, just like the legacy devtools.
> chore: expand component tree item by double clicking it

- packages/overlay/src/App.vue
- packages/overlay/src/composables/panel.ts
closes #411
Hide the panel when enabling the inspector, and restore the state when disabling the inspector.
Use the `escape` shortcut to disable the inspector quickly.
https://github.com/vuejs/devtools-next/assets/49969959/08ee0fe0-3e3d-4ed1-8867-18c0d17eff31
> fix(overlay): hide panel when enable inspector

- packages/vite/src/vite.ts
Removed the unused `DeepRequired` type definition from vite.ts.
> chore(vite): remove unused type definition

- packages/client/src/components/pages/RoutePathItem.vue
- packages/client/src/components/pages/__test__/routePathItem.test.ts
- vitest.config.ts
fix: #432
- Fix the split regex on matching the dynamic parameters.
- Add auto-import to vitest config.
> fix(client): fix mismatching on regex route path

- packages/vite/src/vite.ts
> fix(vite): normalize separate window url when apply `base` option

- docs/.vitepress/config.ts
Once https://github.com/vuejs/create-vue/pull/523 is merged and the new template snapshot is created — `devtools` link will be updated to `devtools-router-pinia`. After merging this PR, playground will showcase Router & Pinia tabs.
Waiting for snapshot generation - https://github.com/vuejs/create-vue-templates/tree/069649e4613d3430f930935e2dbdb76a6a80ab2e
> docs: update playground link [ci skip]

- packages/client/src/pages/settings.vue
should close #458, need test by @sxcooler, test on my local works properly.
Reproduction step:
1. open the page with the devtools floating panel
2. open a separate window
3. update settings on floating panel
4. go to the separate window, and storage is changed, but UI is not changed.
> fix(client): sync state between separate window with floating panel

- packages/client/src/pages/settings.vue
We don't need to show `feature settings` on the `browser extension` / `electron`.
> feat(client): only show feature settings on iframe/seperate-window

- packages/chrome-extension/manifest.json
- packages/firefox-extension/manifest.json
firefox:
chrome
They have indicated that using ‘wasm-unsafe-eval’ in the content policy to execute wasm is supported as the minimal permission.
> feat(browser-ext): update content_security_policy to support wasm

- packages/applet/package.json
- packages/applet/src/composables/shiki.ts
- packages/client/package.json
- packages/client/src/composables/shiki.ts
- pnpm-lock.yaml
I don't now why it was locked as a fixed version, but there should not be any breaking changes for that. Current version range would cause Nuxt DevTools to have multiple version of Shiki installed
> fix: update shiki and relax version range

- packages/applet/src/components/basic/CodeBlock.vue
- packages/applet/src/modules/components/components/RenderCode.vue
Before:
https://github.com/vuejs/devtools-next/assets/49969959/cf374c78-35f5-4752-8502-32ce22890071
After:
https://github.com/vuejs/devtools-next/assets/49969959/5b0c6820-b961-4da8-9665-e8995459d240
> feat(client): improve `RenderCode` component style

- packages/applet/src/components/state/StateFieldViewer.vue
> fix(client): hide state field display on edit

- packages/client/src/pages/assets.vue
- packages/core/src/rpc/types.ts
- packages/playground/basic/assets/asset-in-root-assets.md
- packages/playground/basic/public/assets/asset-in-public-assets.md
- packages/vite/src/rpc/assets.ts
This PR is to close #510.
Todolist
> feat: group assets in duplicate paths between root and public by relativePath

- packages/ui/scripts/update-icons.ts
On Windows, the value obtained by `new URL(import.meta.url).pathname` is prefixed with `/`, which will cause an error in `__dirname`.
> build(ui): normalize dirname for compatibility with the Windows platform

- packages/client/src/components/graph/GraphDrawer.vue
When the file path is long, ellipsis appears, making it difficult to view the complete file path.
> feat(client): truncate button add title attribute

- docs/help/faq.md
WXT has [preconfigured module](https://wxt.dev/guide/key-concepts/frontend-frameworks.html#built-in-modules) for Vue, which is more suitable than `@vitejs/plugin-vue` here.
> docs: use `@wxt-dev/module-vue` instead of `@vitejs/plugin-vue` in faq

- packages/devtools-kit/src/core/component/state/custom.ts
- packages/devtools-kit/src/core/component/state/is.ts
- packages/devtools-kit/src/core/component/state/process.ts
- packages/devtools-kit/src/core/component/state/replacer.ts
- packages/devtools-kit/src/core/component/utils/index.ts
- packages/devtools-kit/src/shared/transfer.ts
closes #542, improve property check.
Benchmark:
- 1. [use typeof object === 'object' && object !== null](https://perf.link/#eyJpZCI6IjJuNGJzeWluY21mIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IG9iaiA9IHt9IiwidGVzdHMiOlt7Im5hbWUiOiJUZXN0IENhc2UiLCJjb2RlIjoidHlwZW9mIG9iaiA9PT0gJ29iamVjdCcgJiYgb2JqICE9PSBudWxsIiwicnVucyI6WzEyNzMxMDAwLDEwMjYwMDAsMTQ2MDkwMDAsMTU4MzAwMCwxMDc5MzAwMCwxOTYwMDAsNjMzMDAwMCw5MzM0MDAwLDE0ODAwMDAsMTExMzAwMDAsNjMyMDAwMCw4MDM2MDAwLDM3NDAwMDAsNTQ4OTAwMCw3NTY4MDAwLDU0MjgwMDAsNzQ1OTAwMCw5MTkwMDAwLDE0ODQwMDAsOTI1NzAwMCwxMDgzMDAwMCwxNDM1ODAwMCwxMTk0MjAwMCwxODYyMzAwMCwxNDg0MDAwLDExMTczMDAwLDkxODEwMDAsMjU2NjAwMCwxNzAwMzAwMCwyOTk3MDAwLDExNjk3MDAwLDgzOTYwMDAsODc0ODAwMCwxOTk3MTAwMCwyNzc4MDAwLDEyNTUyMDAwLDUwOTUwMDAsOTQ2MzAwMCwyMDAwMCwzNTUxMDAw …
> refactor(kit): refactor property checks

- packages/devtools-kit/__tests__/component/decode-state.test.ts
- packages/devtools-kit/src/core/component/state/custom.ts
- packages/playground/basic/src/pages/Home.vue
> fix(kit): should access value on `ObjectRefImpl` and `GetterRefImpl`

- packages/devtools-kit/src/core/vm/index.ts
when i want to debug my vueapp running in node env, this throw a window not defined error
> fix(kit): `exposeInstanceToWindow` work failed in no-browser env

- packages/applet/src/index.ts
Currently, we highly depend on `unocss`, so we didn’t anticipate that someone would use `@vue/devtools-applet` without also using `unocss`. That causes the class names of `devtool-ui` to not be extracted.
> fix(applet): intergration ui package's unocss style

- .node-version
Let node version managers auto-switch to `lts-latest` node version.
> chore: add .node-version

- packages/shared/src/env.ts
I have set-up a laravel, inertia and vue project and integrated devtools-next but kept getting errors on running vite:
```bash
failed to load config from {project dir}/vite.config.js
error when starting dev server:
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
```
The first conditional in `isInElectron` checks if the navigator class exists, it does but it is empty - so the `userAgent` is undefined. I've added an optional chain to the end of the userAgent to ensure it's existence.
> fix(shared): add optional chain to `isInElectron` env

- packages/devtools-kit/src/core/component/utils/index.ts
- packages/playground/basic/src/components/IndexComponent/index.vue
- packages/playground/basic/src/pages/Home.vue
- packages/shared/src/general.ts
Similar to https://github.com/vuejs/devtools-v6/pull/1994
Sometimes developers have components nested inside directories and follow classic Node approach of naming them `/index.${extension}`, in this case `/index.vue`. Devtools currently display every component as `<Index>` unless you specify name. This PR will check for those components and use parent directory as component name.
> feat(kit): for better naming of `index.vue` components

- packages/applet/src/components/state/StateFieldViewer.vue
This PR slightly improves UX for string value inspect. 
Currently sometimes when text is too long and may contains multiple line, it's a bit inconvenient to inspect the whole value. 
This PR adds `title` attribute to solve this.
https://github.com/user-attachments/assets/906abbd5-5b67-401b-9748-ba42fbc67815
> feat(client): show full text on hover for component state field viewer

- packages/devtools-kit/src/shared/transfer.ts
> fix(kit): detect vue doubly-linked node to avoid circular references on encoding

- packages/client/src/components/timeline/TimelineLayers.vue
Currently, the toggle shows the state of the layer after a click. In other words, it shows the opposite of the current state.
With this, the toggle shows the action when clicked.
> chore: fix typo for toggle timeline layer visibility

- packages/devtools-kit/src/shared/transfer.ts
> fix(kit): add null-safety check to detect vue reactive linked list node

- packages/applet/src/composables/custom-inspector-state.ts
- packages/applet/src/modules/components/index.vue
- packages/applet/src/modules/custom-inspector/components/state/Index.vue
- packages/applet/src/modules/custom-inspector/index.vue
- packages/applet/src/modules/pinia/components/store/Index.vue
- packages/applet/src/modules/pinia/constants.ts
- packages/applet/src/modules/pinia/index.vue
- packages/applet/src/utils/search.ts
- packages/devtools-kit/src/ctx/hook.ts
- packages/devtools-kit/src/ctx/inspector.ts
closes #657 
Leave a Todo here, The pinia applet is very similar to the custom inspector applet, we should extract the common logic into a composable.
> feat: filter tree/states for custom inspectors

- packages/devtools-kit/src/ctx/hook.ts
- packages/devtools-kit/src/ctx/inspector.ts
This is a hotfix to #664, the PR removes some state on devtools-kit which will causes some feature crash.
Closes #669
> fix: revert devtools-kit removals in #664

- packages/applet/src/components/timeline/index.vue
- packages/applet/src/modules/components/index.vue
- packages/applet/src/modules/custom-inspector/components/state/Index.vue
- packages/applet/src/modules/pinia/components/store/Index.vue
- packages/applet/src/modules/router/components/routes/Index.vue
> fix(applet): remove select-none on StateViewer

- packages/applet/src/components/state/StateFieldViewer.vue
- packages/devtools-kit/src/core/component/state/process.ts
- packages/devtools-kit/src/core/component/state/util.ts
- packages/playground/basic/src/pages/Home.vue
The `getSetupStateType` will try to access the Proxy by some flag to judge whether the Proxy is a reactivity or not. If the getter fail, for example, the getter do function call, then the inspection would down.
By wrapping `getSetupStateType` in try...catch block could avoid this situation, but will still get the wrong *value*.
If we have a way to display the Proxy in the StateViewer properly would be impressive.
> fix(kit): inspect error with top-level `Proxy` value

- packages/client/src/App.vue
- packages/client/src/assets/styles/main.css
- packages/client/src/components/common/DockingPanel.vue
- packages/client/src/composables/state.ts
- packages/client/src/pages/graph.vue
- packages/client/src/pages/settings.vue
- packages/overlay/src/App.vue
- packages/overlay/src/components/FrameBox.vue
- packages/overlay/src/composables/state.ts
cloese #547.
Now we only align with `preferred-reduce-motion` to solve the consistency.
> feat: respect preferred-reduce-motion

- packages/applet/src/modules/components/index.vue
- packages/core/src/rpc/global.ts
- packages/devtools-kit/src/core/component-highlighter/index.ts
- packages/devtools-kit/src/core/plugin/index.ts
- packages/devtools-kit/src/ctx/api.ts
- packages/playground/multi-app/src/App.vue
- packages/playground/multi-app/src/App2.vue
- packages/playground/multi-app/src/components/Number.vue
Try to fix https://github.com/vuejs/devtools/issues/718
* Call `toggleApp` if the activeAppRecordId is different from the inspected component's app id
* Add `options` to `toggleApp` and related methods, so `{ inspectingComponent: true }` can eventually be sent to core's `registerDevToolsPlugin` to ignore `highPerfModeEnabled`
> fix: switch to relevant app when inspecting component

- packages/vite/src/vite.ts
While working on https://github.com/unocss/unocss/pull/4361 (which takes great inspiration from Vue Devtools, thanks!), I noticed that there is a newline character that introduces trailing between the console output of any other Vite plugin. We seem to assume that Vue Devtools is the only plugin that will print to the console, however that might not always be true (as seen in the linked's PR screenshot).
Though the issue this PR is tackling is a nitpick, I believe it's better to no show any space at all between the help commands rather than force all plugins to have `enforce: 'pre'` or mess up with the "styling" of the console output.
> chore(vite): remove newline on server urls

- packages/vite/src/vite.ts
`server.headers` in vite configuration is now ignored by `__devtool__` related requests, which are handled by `sirv`.
This PR applies `server.headers` in vite configuration to these requests' response.
This PR fixes #565.
> fix(vite): add configured headers for devtool-related response

- packages/applet/src/modules/router/components/routes/Index.vue
> feat(applet): support filter on router page

- packages/devtools-api/package.json
Currently, the api isn't tree shaken when building.
Closes https://github.com/vuejs/pinia/issues/2910
This can be reproduced with https://github.com/vuejs/pinia/tree/v3/packages/size-check. In v6, this was added at https://unpkg.com/browse/@vue/devtools-api@6.6.4/package.json
> fix(api): allow treeshaking

- packages/devtools-kit/__tests__/component/decode-state.test.ts
- packages/devtools-kit/src/core/component/state/custom.ts
since https://github.com/vuejs/core/pull/11539, customRefs's value has cached, so we should access the value first.
see the logic of getObjectDetails
```ts
// ...
const value = toRaw(info.reactive ? object : tryGetRefValue(object))
/**
* - ObjectRefImpl, toRef({ foo: 'foo' }, 'foo'), `_value` is the actual value, (since 3.5.0)
* - GetterRefImpl, toRef(() => state.foo), `_value` is the actual value, (since 3.5.0)
* - RefImpl, ref('foo') / computed(() => 'foo'), `_value` is the actual value
*/
function tryGetRefValue(ref: { _value?: unknown } | { value?: unknown }) {
if (ensurePropertyExists<{ _value?: unknown }>(ref, '_value', true)) {
return ref._value
}
if (ensurePropertyExists(ref, 'value', true)) {
return ref.value
}
}
```
> chore: update test case to align with vue behavior

- .vscode/settings.json
- package.json
- packages/devtools-kit/src/core/component/state/process.ts
- pnpm-lock.yaml
This feature is now enabled by default.  See https://eslint.org/docs/latest/flags/#inactive-flags
> chore: remove `unstable_ts_config` ESLint flag

- packages/devtools-kit/__tests__/component/editor.test.ts
- packages/devtools-kit/src/core/component/state/editor.ts
Currently, modifying a nested object in a Map in Pinia causes an error.
This PR contains a fix for that issue and a new test.
> fix: resolve `Map` nested object modification

- package.json
After pnpm 10 lifecycle scripts of dependencies are not executed during installation by default!  https://github.com/pnpm/pnpm/releases/tag/v10.0.0
> chore: add `onlyBuiltDependencies` list

- packages/applet/src/modules/components/index.vue
- packages/core/src/rpc/global.ts
- packages/devtools-kit/src/core/app/index.ts
- packages/devtools-kit/src/core/iframe/index.ts
- packages/devtools-kit/src/core/index.ts
- packages/devtools-kit/src/types/app.ts
- packages/playground/multi-app/index.html
- packages/playground/multi-app/src/components/Iframe/index.vue
- packages/playground/multi-app/src/components/Iframe/srcdoc.html
- packages/playground/multi-app/src/main.ts
closes #498 
We should inject the hook into the iframe as a script tag, which means the whole hook logic should be serialized. 
We need to discuss it. /cc @webfansplz
> feat(kit): support devtools in iframe

- packages/applet/src/modules/components/index.vue
Would close part of https://github.com/vuejs/devtools/issues/876
> feat: support for keyboard on component tab
