vuejs/devtools

- packages/client/src/pages/components.vue
- packages/overlay/src/composables/panel.ts
> feat: minimize panel while inspecting component node

- packages/client/src/composables/state-tab.ts
For a reproduction, check out the video below:
https://github.com/vuejs/devtools-next/assets/3993028/d54a4a03-1e30-4a18-8686-9f4cf7c29cf1
> fix(client): logic of hidden tabs and categories

- packages/client/src/components/common/SideNav.vue
Fixes the issue of the following picture:
> fix(client): zIndex conflict of SideNav

- packages/client/src/components/inspector/InspectorStateField.vue
> fix(client): expected display of nested objects

- packages/devtools-kit/src/core/plugins/components.ts
> perf: reduce the performance cost of component changed

- packages/devtools-kit/src/api/plugin.ts
Closes #148 
Be related to [vue-query issue](https://github.com/TanStack/query/issues/6632)
> fix: compatible with `vue-query`

- packages/client/src/pages/components.vue
Closes #143 
Be related to https://github.com/vuejs/devtools-next/issues/135#issuecomment-1876673599
> fix(client): expand all parent nodes on inspecting component tree

- docs/guide/standalone.md
- packages/electron/package.json
- packages/electron/src/index.ts
> fix(electron): use esm instead of iife to load script

- packages/client/src/components/common/DockingPanel.vue
- packages/ui/src/components/DarkToggle.vue
- packages/ui/storybook/DarkToggle.story.vue
> fix(ui): destructure slot data binding for `DarkToggle` component

- packages/shared/src/general.ts
> fix(shared): handle circular reference for deep clone

- packages/devtools/package.json
> fix(devtools): error types declaration exports

- packages/electron/src/cli.ts
> fix(electron): decode app file path

- packages/client/src/components/graph/GraphNavbar.vue
closes #178 
https://github.com/vuejs/devtools-next/assets/49969959/eb0ae197-05bb-4b26-84d8-7e70117de4a2
> feat(client): responsive adaptation for graph page

- packages/core/src/vite-rpc/assets.ts
This PR is to close #183.
scope: `assets`
- add `yml/yaml/toml` extensions
- update `fast-glob` ignore rules
> feat(assets): add yml/yaml/toml extensions and update ignore rules

- packages/client/src/components/common/SideNav.vue
> fix(client): make `SideNav` component zIndex be max

- packages/vite/src/vite.ts
> fix(vite): make devtools initialize before app created

- packages/client/src/App.vue
- packages/client/src/components/assets/AssetDetails.vue
- packages/client/src/components/graph/GraphDrawer.vue
- packages/client/src/components/pages/RoutesTable.vue
- packages/client/src/composables/open-in-editor.ts
- packages/client/src/pages/components.vue
- packages/core/src/bridge/core.ts
- packages/devtools-kit/src/core/vue-inspector/index.ts
- packages/devtools-kit/src/index.ts
- packages/devtools-kit/src/shared/util.ts
- packages/overlay/src/App.vue
- packages/playground/vite.config.ts
- packages/vite/src/overlay.js
- packages/vite/src/vite.ts
> feat(vite): introducing component inspector option

- packages/devtools-kit/package.json
> fix(kit): mark vue as peer dependencies

- docs/guide/contributing.md
Easier to copy paste and also consistent with other commands
> docs: remove `$` in command

- packages/devtools-kit/src/core/component/state/editor.ts
- packages/playground/basic/src/stores/index.ts
Fix set/delete procedure on editing native Map/Set.
https://github.com/vuejs/devtools-next/assets/22590005/9781e214-e56a-40da-9593-ec022fb7bfeb
> feat(devtools-kit): enable editing native Map/Set in input field

- tsconfig.json
This is annoying
So I fixed it :)
> chore: fix tsc error in root tsconfig file [ci skip]

- packages/client/src/pages/components.vue
| Before | After |
|--------|--------|
| ![image](https://github.com/vuejs/devtools-next/assets/45714701/e74d7a3b-e266-4dd5-8469-85cc1ba41e52)| ![image](https://github.com/vuejs/devtools-next/assets/45714701/f58bb70d-7540-486b-81fb-274375552674)|
> feat(client): responsive layout for components panel

- packages/core/src/bridge/api.ts
- packages/core/src/vite-bridge/client.ts
> fix(core): use non-secure nanoid for friendly-browser support

- packages/vite/src/modules/assets.ts
Support extension capitalization.
> feat(vite): use case-insensitive mode for matching assets files

- packages/devtools-kit/src/core/component-highlighter/index.ts
> fix(kit): use event-capturing mode when enable component highlighter

- packages/client/src/App.vue
> feat(client): improve UX when toggle sidebar

- packages/client/src/pages/components.vue
> chore(client): align action icons to center

- turbo.json
> chore: fix turbo task pipeline ordering

- packages/devtools-kit/src/plugins/component.ts
Closes #324 
Closes #318 
Closes #310
> fix(kit): sync instanceMap when appRecord matched

- docs/guide/vite-plugin.md
- packages/client/src/composables/open-in-editor.ts
- packages/devtools-kit/src/core/open-in-editor/index.ts
- packages/devtools-kit/src/index.ts
- packages/vite/package.json
- packages/vite/src/modules/get-config.ts
- packages/vite/src/overlay.js
- packages/vite/src/vite.ts
- pnpm-lock.yaml
Closes #251 
Closes #123
Be related to:
https://github.com/webfansplz/vite-plugin-vue-devtools/issues/241
https://github.com/webfansplz/vite-plugin-vue-devtools/issues/206
> fix(vite): apply vite server base url

- packages/client/src/pages/components.vue
| Before | After |
|--------|--------|
| ![EqzrBQLoV9](https://github.com/vuejs/devtools-next/assets/45714701/f6b34c6a-c76b-4839-9c97-80bb4697b728) | ![EZVsSgWYdd](https://github.com/vuejs/devtools-next/assets/45714701/5dcb00cc-c7d5-4adf-834d-a6d5e29ce5a4)|
> feat(client): auto scroll to component tree after inspected

- packages/applet/src/components/state/StateFieldEditor.vue
- packages/applet/src/components/state/StateFieldViewer.vue
- packages/devtools-kit/src/core/component/types/state.ts
- packages/playground/basic/src/stores/index.ts
fix: #349
Add path property to address the correct path.
> fix(applet): make sure `a.b` property displays/edits as expected

- packages/client/src/components/graph/GraphDrawer.vue
- packages/client/src/pages/assets.vue
- packages/ui/src/components/Dialog.vue
- packages/ui/src/components/Drawer.vue
- packages/ui/src/components/Overlay.vue
fixes this:
https://github.com/vuejs/devtools-next/assets/49969959/539789cf-0cef-4eea-be93-60aec0d025c1
> fix(client): drawer positions

- packages/client/data/vue-apis.json
- scripts/vue-api-manifest.ts
update `vue-api-manifest`, remove ` symbol for more clear title/desc
> feat(client): update vue-api-manifest

- docs/guide/faq.md
- docs/guide/vite-plugin.md
- packages/playground/basic/vite.config.ts
- packages/vite/package.json
- packages/vite/src/vite.ts
- pnpm-lock.yaml
> feat: `launchEditor` option

- docs/guide/vite-plugin.md
> doc: update vite-plugin.md [ci skip]

- docs/guide/faq.md
Fixed Laravel Vite plugin config - DevTools to VueDevTools
> docs: fix typo [ci skip]

- packages/devtools-kit/src/core/index.ts
- packages/playground/multi-app/src/main.ts
Reverts vuejs/devtools-next#357
Closes #392 
/cc @alexzhang1030 We may find a better way to handle it.
> fix: page can't navigation, revert #357

- packages/overlay/vite.config.ts
- packages/playground/basic/package.json
- packages/playground/basic/vite.config.ts
- packages/vite/src/overlay.js
- pnpm-lock.yaml
> fix(vite+overlay): using mjs overlay bundle for vite plugin

- packages/applet/src/components/state/StateFieldViewer.vue
- packages/applet/uno.config.ts
- packages/devtools-kit/__tests__/component/format.test.ts
- packages/devtools-kit/src/core/component/state/format.ts
- packages/playground/applet/src/stores/index.ts
> feat(applet): improve long-string display in components panel

- packages/applet/src/components/timeline/EventList.vue
closes #428 
https://github.com/vuejs/devtools-next/assets/49969959/bd2adba6-c60a-4276-b8ca-db9d0d182072
> feat(applet): auto scroll to bottom when timeline event updated

- packages/devtools-kit/src/core/plugin/components.ts
- packages/devtools-kit/src/core/vm/index.ts
- packages/devtools-kit/src/ctx/hook.ts
closes #426 
Works with vite-plugin & chrome-extension
https://github.com/vuejs/devtools-next/assets/49969959/74a0c9d4-f2dd-4df7-bada-7072242f7283
> feat(core): expose activeComponent to window

- docs/help/faq.md
Improvements in documentation about #436
> docs: add `WXT` usage in FAQs page

- packages/client/src/pages/settings.vue
> fix(client): expand settings grid column width

- packages/devtools-kit/src/core/index.ts
- packages/devtools-kit/src/core/plugin/index.ts
- packages/devtools-kit/src/ctx/api.ts
- packages/playground/basic/package.json
- packages/playground/basic/src/main.ts
- packages/playground/basic/vite.config.ts
- pnpm-lock.yaml
> fix(kit): prevent duplicate registration of devtool plugin

- packages/ui/package.json
- packages/ui/vite.config.ts
> build(ui): fix incompatiable with ts v5.5

- packages/applet/src/components/basic/DevToolsHeader.vue
add title to DevToolsHeader from https://github.com/vuejs/devtools-next/blob/main/packages/applet/src/modules/router/components/Home.vue
> feat(applet): add doc/github title in `DevToolsHeader` component

- packages/applet/src/components/basic/DevToolsHeader.vue
- packages/applet/src/components/basic/Navbar.vue
https://github.com/vuejs/devtools-next/assets/12596485/13ad29fb-aab5-41b9-aa2a-555c1b5738e5
not exactly the best realization, but it'll do for now. 
I'm also not quite sure how best to work locally, open two terminals in the first one 
`pnpm dev` in the second `pnpm play`
but I always have to manually refresh the page to see the changes :( 
what is the right way?
> feat(applet): improve custom inspector page nav style

- packages/applet/src/components/state/RootStateViewer.vue
- packages/applet/src/components/state/StateFieldViewer.vue
- packages/applet/src/components/tree/TreeViewer.vue
- packages/applet/src/modules/components/index.vue
https://github.com/vuejs/devtools-next/assets/49969959/42bd429d-3d60-4d94-acd1-61b885720c6c
> feat(applet): respect ui scale on components panel text-size

- docs/guide/standalone.md
> docs: update standalone app install guide

- packages/client/src/components/common/SplitScreen.vue
- packages/client/src/components/common/TabIcon.vue
Preview:
https://github.com/vuejs/devtools-next/assets/49969959/be426f72-3e67-4658-82cc-136d78937707
> fix(client): customInspectorView on splitScreen

- docs/guide/browser-extension.md
If the ID is removed the language will be the default browser language.
> chore(docs): remove language id in link to chrome webstore

- packages/client/src/components/common/SideNav.vue
This is a better solution of #478 , and bug fixes of #479.
The issue is :
https://github.com/vuejs/devtools-next/assets/49969959/b65be5ab-f4a4-458d-b6d4-997d740102ab
Now:
https://github.com/vuejs/devtools-next/assets/49969959/abb343ff-2fa6-4f8a-977b-8da61b067a68
> refactor(client): reposition `dockingPanel` dropdown on window resize

- packages/applet/src/modules/components/index.vue
- packages/playground/basic/src/main.ts
- packages/playground/basic/src/pages/IntervalUpdate.vue
> fix(applet): stabilize search results when updating component tree

- packages/applet/src/modules/components/index.vue
closes #540 , a mistake-proofing.
> fix(applet): hide select component button on seperate window

- docs/.vitepress/config.ts
- docs/getting-started/open-in-editor.md
- packages/applet/src/modules/components/index.vue
- packages/client/src/composables/open-in-editor.ts
- packages/devtools-kit/src/core/open-in-editor/index.ts
- packages/playground/basic/src/main.ts
> feat(extension): support open-in-editor

- packages/devtools-kit/src/shared/transfer.ts
Close #553 
Be related to https://github.com/vuejs/devtools-next/commit/7c3210365acc73dfc6eb1ae03405ea9e6126a7d2#diff-9696355d8a5c955c55389a9088cbd278a37ccc9f854dd65779072ccfe8549db3R126, /cc @alexzhang1030
> fix(kit): fix call context when stringify with replacer

- packages/chrome-extension/src/devtools-background.ts
- packages/client/src/App.vue
- packages/client/src/components/common/SideNav.vue
- packages/core/src/rpc/global.ts
- packages/devtools-kit/src/core/devtools-client/detected.ts
- packages/devtools-kit/src/ctx/state.ts
- packages/devtools-kit/src/hook/index.ts
- packages/devtools-kit/src/index.ts
- packages/firefox-extension/src/devtools-background.ts
> perf: reduce initial performance overhead

- packages/applet/src/components/settings/Settings.vue
- packages/applet/src/modules/custom-inspector/components/Settings.vue
- packages/applet/src/modules/custom-inspector/index.vue
- packages/applet/src/modules/pinia/components/Settings.vue
- packages/applet/src/modules/pinia/index.vue
- packages/core/src/rpc/global.ts
- packages/devtools-kit/src/api/v6/index.ts
- packages/devtools-kit/src/core/plugin/index.ts
- packages/devtools-kit/src/core/plugin/plugin-settings.ts
- packages/devtools-kit/src/ctx/api.ts
> feat: add settings for devtools plugin

- packages/applet/src/components/state/StateFieldViewer.vue
> fix: normalize reactivity state type

- packages/chrome-extension/src/devtools-panel.ts
> fix(extension): re-run script when execution context is empty

- packages/applet/src/components/tree/TreeViewer.vue
- packages/devtools-kit/src/api/v6/index.ts
- packages/devtools-kit/src/core/app/index.ts
- packages/devtools-kit/src/core/component/tree/walker.ts
- packages/devtools-kit/src/core/component/utils/index.ts
- packages/devtools-kit/src/core/index.ts
- packages/devtools-kit/src/core/plugin/components.ts
- packages/devtools-kit/src/hook/index.ts
- packages/devtools-kit/src/types/hook.ts
> feat: add node tags for component tree

- packages/client/package.json
- packages/client/vite.base.config.ts
- packages/overlay/package.json
- packages/overlay/vite.config.ts
- packages/playground/applet/package.json
- packages/playground/applet/vite.config.ts
- packages/playground/basic/package.json
- packages/playground/basic/vite.config.ts
- packages/playground/multi-app/package.json
- packages/playground/multi-app/vite.config.ts
- pnpm-lock.yaml
related https://github.com/vitejs/vite/issues/18164
> chore: use sass modern api

- packages/devtools-kit/src/core/component/state/editor.ts
- packages/devtools-kit/src/core/component/state/process.ts
- packages/playground/basic/src/App.vue
- packages/playground/basic/src/components/PropChild.vue
- packages/playground/basic/src/main.ts
- packages/playground/basic/src/pages/PropMutation.vue
> feat(kit): editable component props

- docs/getting-started/introduction.md
Just a small grammar fix here. :)
> chore: fix typo [ci skip]

- packages/playground/applet/package.json
- packages/playground/basic/package.json
- packages/playground/multi-app/package.json
- packages/vite/package.json
- pnpm-lock.yaml
> feat: support `vite-plugin-inspect` for both Vite 5 and 6
